MODEL = 'Model'
VRAM = 'VRAM'
VRAM_USAGE = 'VRAM Usage'
TEMP = 'Temp'
GPU_FREQ = 'GPU Freq'
MEM_FREQ = 'Mem Freq'
PCI_SLOT = 'PCI Slot'
GPU_VOLT = 'GPU Voltage'

DYNAMIC_GPU_PROPERTIES = [TEMP, GPU_FREQ, MEM_FREQ, VRAM_USAGE, GPU_VOLT]