#!/bin/sh
# postrm script for slimbookamdcontroller
#
# see: dh_installdeb(1)

set -e
set -x

#Deleting
cd /usr/share/slimbookamdcontroller/
rm -rf RyzenAdj/
rm -rf ryzenadj
#rm -rf /home/*/.config/slimbookamdcontroller

pip uninstall pyamdgpuinfo -y

exit 0

