#!/bin/sh

set -e

# Cloning ryzenadj
cd /usr/share/slimbookamdcontroller/
git clone https://github.com/FlyGoat/RyzenAdj.git
cd RyzenAdj/
# Compilation
mkdir build
cd build
cmake ..
make
cp ryzenadj ../../
chmod +x /usr/share/slimbookamdcontroller/ryzenadj

# App Permisions
chmod +x /usr/lib/systemd/system-sleep/slimbookamdcontroller
chmod -R 755 /usr/share/slimbookamdcontroller/src

/usr/share/slimbookamdcontroller/src/configuration/check_config.py

exit 0
