Document: slimbookamdcontroller
Title: Debian slimbookamdcontroller Manual
Author: <insert document author here>
Abstract: This manual describes what slimbookamdcontroller is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/slimbookamdcontroller/slimbookamdcontroller.sgml.gz

Format: postscript
Files: /usr/share/doc/slimbookamdcontroller/slimbookamdcontroller.ps.gz

Format: text
Files: /usr/share/doc/slimbookamdcontroller/slimbookamdcontroller.text.gz

Format: HTML
Index: /usr/share/doc/slimbookamdcontroller/html/index.html
Files: /usr/share/doc/slimbookamdcontroller/html/*.html
